## Card illustrations (split from SpriteRegistry, GID-151): creature portraits
## and spell-branch runes generated by tools/generate_cards.py. Literal
## preloads only (Android).
extends RefCounted

const _CARD_GHOST         := preload("res://assets/textures/cards/card_ghost.png")
const _CARD_SKELETON      := preload("res://assets/textures/cards/card_skeleton.png")
const _CARD_ZOMBIE        := preload("res://assets/textures/cards/card_zombie.png")
const _CARD_GHOUL         := preload("res://assets/textures/cards/card_ghoul.png")
const _RUNE_DAWN          := preload("res://assets/textures/cards/rune_dawn.png")
const _RUNE_DUSK          := preload("res://assets/textures/cards/rune_dusk.png")
const _RUNE_EMBER         := preload("res://assets/textures/cards/rune_ember.png")
const _RUNE_ASH           := preload("res://assets/textures/cards/rune_ash.png")
const _RUNE_BLOOM         := preload("res://assets/textures/cards/rune_bloom.png")
const _RUNE_THORN         := preload("res://assets/textures/cards/rune_thorn.png")
const _RUNE_FLUX          := preload("res://assets/textures/cards/rune_flux.png")
const _RUNE_FRACTURE      := preload("res://assets/textures/cards/rune_fracture.png")
const _CARD_WOLF              := preload("res://assets/textures/cards/card_wolf.png")
const _CARD_WOLF_PACK         := preload("res://assets/textures/cards/card_wolf_pack.png")
const _CARD_SCARAB            := preload("res://assets/textures/cards/card_scarab.png")
const _CARD_SCARAB_SWARM      := preload("res://assets/textures/cards/card_scarab_swarm.png")
const _CARD_BARROW_KING       := preload("res://assets/textures/cards/card_barrow_king.png")
const _CARD_BOG_HAG           := preload("res://assets/textures/cards/card_bog_hag.png")
const _CARD_EMBER_CULTIST     := preload("res://assets/textures/cards/card_ember_cultist.png")
const _CARD_RIFT_ECHO         := preload("res://assets/textures/cards/card_rift_echo.png")
const _CARD_SCOUT             := preload("res://assets/textures/cards/card_scout.png")
const _CARD_RAIDER            := preload("res://assets/textures/cards/card_raider.png")
const _CARD_WENDIGO           := preload("res://assets/textures/cards/card_wendigo.png")
const _CARD_WARLEADER         := preload("res://assets/textures/cards/card_warleader.png")
const _CARD_TERROR            := preload("res://assets/textures/cards/card_terror.png")
const _CARD_UNDEAD_ELITE      := preload("res://assets/textures/cards/card_undead_elite.png")
const _CARD_WORM              := preload("res://assets/textures/cards/card_worm.png")
const _CARD_STAG              := preload("res://assets/textures/cards/card_stag.png")
const _CARD_DUELIST           := preload("res://assets/textures/cards/card_duelist.png")
const _CARD_RIVAL             := preload("res://assets/textures/cards/card_rival.png")
const _CARD_MONK              := preload("res://assets/textures/cards/card_monk.png")
const _CARD_HERBALIST         := preload("res://assets/textures/cards/card_herbalist.png")
const _CARD_TRAINER           := preload("res://assets/textures/cards/card_trainer.png")
const _CARD_WARDEN            := preload("res://assets/textures/cards/card_warden.png")
const _CARD_TREANT            := preload("res://assets/textures/cards/card_treant.png")

## Creature card id -> family portrait / rune (GID-151 / TID-640).
const _CARD_ART: Dictionary = {
	"ancient_guardian": _CARD_STAG,
	"ash_arbiter": _CARD_UNDEAD_ELITE,
	"ash_warden": _CARD_WARLEADER,
	"blitz_ghoul": _CARD_GHOUL,
	"dawn_acolyte": _CARD_MONK,
	"dawn_guardian": _CARD_WARDEN,
	"dawn_healer": _CARD_HERBALIST,
	"dawn_paladin": _CARD_TRAINER,
	"duel_crown": _CARD_DUELIST,
	"dusk_seer": _CARD_BOG_HAG,
	"dusk_vampire": _CARD_RIVAL,
	"dusk_wraith": _CARD_GHOST,
	"ember_imp": _CARD_EMBER_CULTIST,
	"iron_revenant": _CARD_TERROR,
	"isfig_shadow_echo": _CARD_RIVAL,
	"phoenix_rise": _RUNE_EMBER,
	"pyre_warden": _CARD_EMBER_CULTIST,
	"scarab": _CARD_SCARAB,
	"shrouded_wraith": _CARD_GHOST,
	"sig_alpha_wolf": _CARD_WOLF,
	"sig_barrow_crown": _CARD_BARROW_KING,
	"sig_cauldron_toad": _CARD_BOG_HAG,
	"sig_cinder_acolyte": _CARD_EMBER_CULTIST,
	"sig_echo_shard": _CARD_RIFT_ECHO,
	"sig_pack_leader": _CARD_WOLF_PACK,
	"sig_pathfinder": _CARD_SCOUT,
	"sig_scarab_matriarch": _CARD_SCARAB_SWARM,
	"sig_shambler": _CARD_ZOMBIE,
	"sig_wanderer": _CARD_RAIDER,
	"sig_warlord": _CARD_WARLEADER,
	"sig_wendigo_antler": _CARD_WENDIGO,
	"soul_harvest": _RUNE_DAWN,
	"surge_spirit": _CARD_RIFT_ECHO,
	"time_warp": _RUNE_FLUX,
	"treant": _CARD_TREANT,
	"veiled_paladin": _CARD_DUELIST,
	"void_creeper": _CARD_WORM,
	"void_wyrm": _CARD_TERROR,
	"wolf": _CARD_WOLF,
}

## Maps a card illustration key + magic branch to its texture.
## illus_key is a card id (minions / legendaries, via _CARD_ART) or "spell"
## (any non-creature key) for spell cards, which route by magic_branch
## instead. Returns null for an unrecognized key/branch combination —
## caller falls back to TextureGen.card_illustration().
static func illustration(illus_key: String, magic_branch: String) -> Texture2D:
	match illus_key:
		"ghost":    return _CARD_GHOST
		"skeleton": return _CARD_SKELETON
		"zombie":   return _CARD_ZOMBIE
		"ghoul":    return _CARD_GHOUL
	if _CARD_ART.has(illus_key):
		return _CARD_ART[illus_key] as Texture2D
	match magic_branch:
		"dawn":  return _RUNE_DAWN
		"dusk":  return _RUNE_DUSK
		"ember": return _RUNE_EMBER
		"ash":   return _RUNE_ASH
		"bloom": return _RUNE_BLOOM
		"thorn": return _RUNE_THORN
		"flux":  return _RUNE_FLUX
		"fracture": return _RUNE_FRACTURE
	return null
