## Card chrome textures (GID-151): the per-magic-type frames, the shared card
## back + crest, and the cost gem / stat badges / text plate that dress a card
## face. Generated by tools/generate_card_frames.py. Literal preloads only
## (Android). scenes/ui/CardFace.gd turns these into sized styleboxes.
extends RefCounted

## Border width in source pixels; must match MARGIN in the generator.
const FRAME_MARGIN := 6
## Text plate border width in source pixels.
const PLATE_MARGIN := 3

const _FRAME_LIGHT   := preload("res://assets/textures/cards/frame_light.png")
const _FRAME_DARK    := preload("res://assets/textures/cards/frame_dark.png")
const _FRAME_VERDANT := preload("res://assets/textures/cards/frame_verdant.png")
const _FRAME_RIFT    := preload("res://assets/textures/cards/frame_rift.png")
const _FRAME_NEUTRAL := preload("res://assets/textures/cards/frame_neutral.png")
const _CARD_BACK     := preload("res://assets/textures/cards/card_back.png")
const _CARD_CREST    := preload("res://assets/textures/cards/card_crest.png")
const _GEM_COST      := preload("res://assets/textures/cards/gem_cost.png")
const _BADGE_ATK     := preload("res://assets/textures/cards/badge_atk.png")
const _BADGE_HP      := preload("res://assets/textures/cards/badge_hp.png")
const _PLATE_TEXT    := preload("res://assets/textures/cards/plate_text.png")

const _FRAMES: Dictionary = {
	"light": _FRAME_LIGHT,
	"dark": _FRAME_DARK,
	"verdant": _FRAME_VERDANT,
	"rift": _FRAME_RIFT,
}

## Frame for a MagicTypes type; unknown / empty types get the neutral frame.
static func frame_texture(magic_type: String) -> Texture2D:
	return _FRAMES.get(magic_type, _FRAME_NEUTRAL) as Texture2D

static func has_frame(magic_type: String) -> bool:
	return _FRAMES.has(magic_type)

static func back_texture() -> Texture2D:
	return _CARD_BACK

static func crest_texture() -> Texture2D:
	return _CARD_CREST

static func gem_texture() -> Texture2D:
	return _GEM_COST

static func attack_badge_texture() -> Texture2D:
	return _BADGE_ATK

static func health_badge_texture() -> Texture2D:
	return _BADGE_HP

static func plate_texture() -> Texture2D:
	return _PLATE_TEXT
