## GENERATED by tools/bake_realm_map.gd — do not edit. The realm map's baked art:
## terrain per start seed and a plan per stitched town (RealmMapArt), preloaded
## so it ships on Android. RECT is the terrain's tile rect when it was baked.
extends RefCounted

const RECT := Rect2i(-206, -59, 387, 387)

const _T_42 := preload("res://assets/maps/realm/terrain_42.png")
const _T_73856135 := preload("res://assets/maps/realm/terrain_73856135.png")
const _T_100033 := preload("res://assets/maps/realm/terrain_100033.png")
const _T_19349705 := preload("res://assets/maps/realm/terrain_19349705.png")
const _T_294967337 := preload("res://assets/maps/realm/terrain_294967337.png")
const _TOWN_MADRIAN := preload("res://assets/maps/realm/town_madrian.png")
const _TOWN_MAYKALENE := preload("res://assets/maps/realm/town_maykalene.png")
const _TOWN_BLANCOGOV := preload("res://assets/maps/realm/town_blancogov.png")
const _TOWN_LARIK := preload("res://assets/maps/realm/town_larik.png")
const _TOWN_MARSAX_HOLD := preload("res://assets/maps/realm/town_marsax_hold.png")

const _TERRAIN: Dictionary = {
	42: _T_42,
	73856135: _T_73856135,
	100033: _T_100033,
	19349705: _T_19349705,
	294967337: _T_294967337,
}
const _TOWNS: Dictionary = {
	"madrian": _TOWN_MADRIAN,
	"maykalene": _TOWN_MAYKALENE,
	"blancogov": _TOWN_BLANCOGOV,
	"larik": _TOWN_LARIK,
	"marsax_hold": _TOWN_MARSAX_HOLD,
}


## The baked terrain for `world_seed`, or null (paint it live).
static func terrain(world_seed: int) -> Texture2D:
	return _TERRAIN.get(world_seed) as Texture2D


## Town → baked plan texture.
static func towns() -> Dictionary:
	return _TOWNS.duplicate()
