## Bakes the realm map art (RealmMapArt) into assets/maps/realm/: one terrain
## PNG per start seed (BiomeDef.START_SEEDS) and one plan per stitched town, and
## writes game_logic/world/RealmMapBaked.gd, the preload table the realm map reads.
## Re-run after changing world generation, RealmLayout or a town map:
##   godot --headless --path . -s tools/bake_realm_map.gd
##   godot --headless --editor --quit          # import the PNGs
## test_realm_map_art fails while the bake is stale.
extends SceneTree

const DIR: String = "res://assets/maps/realm/"
const TABLE: String = "res://game_logic/world/RealmMapBaked.gd"

# Loaded at run time, not preloaded: the world generators call IsoConst functions,
# which only resolve once the IsoConst autoload exists (after _initialize starts).
var _art: GDScript
var _realm_layout: GDScript
var _world_gen: GDScript


func _initialize() -> void:
	_bake.call_deferred()


func _bake() -> void:
	_art = load("res://game_logic/world/RealmMapArt.gd")
	_realm_layout = load("res://game_logic/world/RealmLayout.gd")
	_world_gen = load("res://game_logic/world/InfiniteWorldGen.gd")
	var start_seeds: Array = (load("res://game_logic/world/BiomeDef.gd") as GDScript).get("START_SEEDS")
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(DIR))
	var rect: Rect2i = _art.call("terrain_rect")
	var lines: Array[String] = [
		"## GENERATED by tools/bake_realm_map.gd — do not edit. The realm map's baked art:",
		"## terrain per start seed and a plan per stitched town (RealmMapArt), preloaded",
		"## so it ships on Android. RECT is the terrain's tile rect when it was baked.",
		"extends RefCounted", "",
		"const RECT := Rect2i(%d, %d, %d, %d)" % [rect.position.x, rect.position.y, rect.size.x, rect.size.y], "",
	]
	var seeds: Array[String] = []
	for s: int in start_seeds:
		_world_gen.call("warm", s)
		(_art.call("terrain_image", rect, s) as Image).save_png(DIR + "terrain_%d.png" % s)
		lines.append("const _T_%d := preload(\"%sterrain_%d.png\")" % [s, DIR, s])
		seeds.append("\t%d: _T_%d," % [s, s])
	var towns: Array[String] = []
	for town: String in _realm_layout.call("town_names"):
		(_art.call("town_image", town) as Image).save_png(DIR + "town_%s.png" % town)
		lines.append("const _TOWN_%s := preload(\"%stown_%s.png\")" % [town.to_upper(), DIR, town])
		towns.append("\t\"%s\": _TOWN_%s," % [town, town.to_upper()])
	lines.append("")
	lines.append("const _TERRAIN: Dictionary = {")
	lines.append_array(seeds)
	lines.append("}")
	lines.append("const _TOWNS: Dictionary = {")
	lines.append_array(towns)
	lines.append("}")
	lines.append_array(["", "",
		"## The baked terrain for `world_seed`, or null (paint it live).",
		"static func terrain(world_seed: int) -> Texture2D:",
		"\treturn _TERRAIN.get(world_seed) as Texture2D", "", "",
		"## Town → baked plan texture.",
		"static func towns() -> Dictionary:",
		"\treturn _TOWNS.duplicate()", ""])
	var f := FileAccess.open(TABLE, FileAccess.WRITE)
	f.store_string("\n".join(lines))
	f.close()
	print("baked realm map: %d seeds, %d towns, rect %s" % [seeds.size(), towns.size(), rect])
	quit()
